### ISSUE TITLE
Connect to BlueDB instance

### ISSUE THREAD

**Issue by Try2BWise** [GregaMohorko/BlueDBClient.NET#1]
This may not be the correct place for this, but how do I connect to a BlueDB instance?

**Comment by GregaMohorko** [comment]
Hi Brandon, Can you please explain in more detail your current setup and what is the issue?

**Comment by Try2BWise** [comment]
Thank you for the reply. I am trying to read data directly from a Xima Chronicall system that uses BlueDB. I have access to the server where Xima is running and know the location of the BlueDB instance (or folders or structure).

SQL is primarily the type of database I work with so I may have some wrong ideas about accessing BlueDB.

**Comment by GregaMohorko** [comment]
Hi Brandon, Sorry for my late reply.

In what way would you like to connect/access it?

BlueDBClient.NET is simply a .NET library to support JSON serialization/deserialization of objects that were serialized with BlueDB.

Example workflow: You use BlueDB on your PHP server to load object A from MySQL database. Then you use BlueDB to serialize this object to JSON text. Then you transfer this JSON (using web service or however) to your app or server that is running in .NET. You then use this BlueDBClient.NET library to deserialize the JSON text back to your object A (that was loaded from the database).

**Comment by GregaMohorko** [comment]
I'm closing this issue since it was created due to misunderstanding this library.

**Comment by Try2BWise** [comment]
Agees. Thank you for the information.

Brandon Wise
